name: presentation
publish_to: none

environment:
  sdk: '>=2.19.0'

dependencies:
  domain:
    path: ../domain
  data:
    path: ../data
  flutter:
    sdk: flutter
  # For Architecture
  flutter_riverpod:
  riverpod_annotation:
  # Dependency Injection
  get_it:
  # For Model
  freezed_annotation:
  # For Navigation
  go_router:
  # For UIs
  gap:
  cupertino_icons:
  google_fonts:
  flutter_svg:
  # For Util
  simple_logger:

dev_dependencies:
  build_runner:
  # For Architecture
  riverpod_generator:
  riverpod_lint:
  # For Assets
  flutter_gen_runner:
  # For Model
  freezed:
  # For Navigation
  go_router_builder:
  # For Analyzer
  custom_lint:
  flutter_lints:
  # For Testing
  mocktail:
  image_test_utils:
    git:
      url: https://github.com/michaelgobbers/image_test_utils
      ref: 6160ecc

flutter_gen:
  integrations:
    flutter_svg: false

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    # - assets/svgs/
    # - assets/videos/
  # fonts:
  #   - family: Rotunda
  #     fonts:
  #       - asset: assets/fonts/Rotunda-Bold.otf
