name: domain

environment:
  sdk: '>=2.19.0'

dependencies:
  flutter:
    sdk: flutter
  # For Architecture
  flutter_riverpod:
  riverpod_annotation:
  # For Networking
  dio:
  retrofit:
  # For Model
  freezed_annotation:
  shared_preferences:
  # For DateTime
  intl:
  # For Util
  simple_logger:
  # For UIs
  gap:
  cupertino_icons:
  google_fonts:
  flutter_svg:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  # For Architecture
  riverpod_generator:
  riverpod_lint:
  # For Networking
  retrofit_generator:
  # For Assets
  flutter_gen_runner:
  # For Model
  freezed:
  json_serializable:
  # For Analyzer
  custom_lint:
  flutter_lints:
  pedantic_mono:
  # For Testing
  mocktail:
  image_test_utils:
    git:
      url: https://github.com/michaelgobbers/image_test_utils
      ref: 6160ecc
