name: domain
publish_to: none

environment:
  sdk: '>=2.19.0'

dependencies:
  flutter:
    sdk: flutter
  # For Architecture
  flutter_riverpod:
  riverpod_annotation:
  # For Networking
  dio:
  # For Model
  freezed_annotation:

dev_dependencies:
  build_runner:
  # For Architecture
  riverpod_generator:
  riverpod_lint:
  # For Model
  freezed:
  json_serializable:
  # For Analyzer
  custom_lint:
  flutter_lints:
